### ISSUE TITLE
在正常配置下 /posts 页面丢失（404）

### ISSUE THREAD

**Issue by rewired-gh** [varkai/hugo-theme-zozo#12]
例如：https://hopp.top/posts

在范例网站中可以正常显示，但是在我自己搭建的网站中无法显示。我已经彻底排查了一遍配置，还是找不到问题。有可能是因为该主题在某次更新后破坏了该功能。

我的代码仓库：https://github.com/h0gan1ee/novela-hugo-starter

**Comment by varkai** [comment]
> 例如：https://hopp.top/posts
> 
> 在范例网站中可以正常显示，但是在我自己搭建的网站中无法显示。我已经彻底排查了一遍配置，还是找不到问题。有可能是因为该主题在某次更新后破坏了该功能。
> 
> 我的代码仓库：https://github.com/h0gan1ee/novela-hugo-starter

hugo的版本是多少？

**Comment by rewired-gh** [comment]
> > 例如：https://hopp.top/posts
> > 在范例网站中可以正常显示，但是在我自己搭建的网站中无法显示。我已经彻底排查了一遍配置，还是找不到问题。有可能是因为该主题在某次更新后破坏了该功能。
> > 我的代码仓库：https://github.com/h0gan1ee/novela-hugo-starter
> 
> hugo的版本是多少？

在 `netlify.toml` 文件中：
```toml
[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.72.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
```
与 ExampleSite 的配置一致。
