### ISSUE TITLE
代码高亮是否可以配置?

### ISSUE THREAD

**Issue by Jiiiiiin** [varkai/hugo-theme-zozo#18]
目前代码高亮、前景和背景颜色反差太大 是否可以配置?

**Comment by varkai** [comment]
> 目前代码高亮、前景和背景颜色反差太大 是否可以配置?

原代码高亮应该是正常的啊，我这边是没什么问题的，如果要改，改 [highlight.css](https://github.com/varkai/hugo-theme-zozo/blob/master/static/css/highlight.css) 这个文件就可以了。

**Comment by jaywhen** [comment]
@Jiiiiiin 
若你是指的下图这种情况：
![highlight](https://cdn.jsdelivr.net/gh/jaywhen/imageBed/imghighlight-error.png)
那么可以检查一下 `config.toml` 文件中的这几行是否被注释掉了：
``` toml
pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true
```
