### ISSUE TITLE
对于 markdown 的粗体 css 渲染问题

### ISSUE THREAD

**Issue by zjuyk** [varkai/hugo-theme-zozo#20]
我发现在 zozo.css 中你将 font-weight 设置为 normal，是否设置为 bold 更为合理？
```css
.markdown strong,
.markdown b,
.markdown em {
  padding: 1px 2px;
  background-color: #fcfcf0;
  font-weight: normal;
}
```
